name: Deploy to S3
on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      account_id:
        description: "AWS Account ID"
        required: true
        default: "058264095432"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure AWS credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ github.event.inputs.account_id }}:role/GitHubActionsTerraformRole
        aws-region: ap-southeast-2
    
    - name: Sync site folder to S3
      run: |
        aws s3 sync site/ s3://${{ secrets.S3_BUCKET_NAME }} \
          --delete \
          --acl public-read \
          --cache-control "max-age=3600"